# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    # configure filters
    #foo.search_filter:
    #    parent: 'api_platform.doctrine.orm.search_filter'
    #    arguments: [ { id: 'exact', bar: 'partial' } ]
    #    tags: ['api_platform.filter']
    poviat.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { voivodship: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        
    commune.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { poviat: 'exact' } ]
        tags: [ 'api_platform.filter' ]        

    department.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { companyId: 'exact' } ]
        tags: [ 'api_platform.filter' ]        

    mobile.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { company: 'exact' } ]
        tags: [ 'api_platform.filter' ] 

    mobileFuelUsed.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { mobile.company: 'exact', periodId: 'exact' } ]
        tags: [ 'api_platform.filter' ] 
